version: '3.4'

services:
  data:
    image: ${DOCKER_REGISTRY-}data
    build:
      context: .
      dockerfile: Data/Dockerfile

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
 
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
    - "1433:1433"
    environment:
      SA_PASSWORD: "tvxs721#3TTv"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "tvxs721#3" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 10s
      retries: 10
 